name: QuarryCraft
version: 1.4.2
main: com.nullbyte.quarrycraft.Main
api-version: 1.13
softdepend: [WorldGuard, GriefPrevention]
commands:
   quarrycraft:
      guide:
         description: Gives the player a QuarryCraft guide book
      trust:
         usage: /quarrycraft trust <player> 
         description: Trust a player to let them access one of your quarry. To do this you must be standing on your quarry chest!
permissions:
   quarrycraft.*:
      description: Grants all quarrycraft permissions
      children:
         quarrycraft.buildquarries: true
         quarrycraft.use: true
         quarrycraft.useall: false
      
   quarrycraft.buildquarries:
      description: Allows the player to actually make their own quarries
      default: true
      
   quarrycraft.use:
      description: Allows the player to interact with their own quarries
      default: true
   
   quarrycraft.useall:
      description: Allows the player to use all quarries
      default: false